### ISSUE TITLE
Error in workflow "Search in Notion"

### ISSUE THREAD

**Issue by jerryyang0611** [spearkkk/alfred-workflow#2]
I've tried to add the token, but it doesn't seem to work.. : (
After adding the token, when I type `no-init`, it always shows like this: 
![image](https://user-images.githubusercontent.com/45359868/114492880-0cbb9680-9c4c-11eb-8152-8ed06e669c65.png)

For the token itself, do you mean the whole cookie (including `notion_users`, `notion_browser_id`, etc ) or just the `token_v2` in the cookie part?

Here is my error message in the Alfred debug mode: 
![image](https://user-images.githubusercontent.com/45359868/114493142-8eabbf80-9c4c-11eb-936f-c110655d4c39.png)

I do expect there's an updating waiting time for this workflow, but after seeing this error message I doubt that possibility. 
Pls drop any hints or help me out :) thxx

**Comment by spearkkk** [comment]
@jerryyang0611 , Hi Thank you for using my workflow.
Did you try this docs? - https://github.com/spearkkk/alfred-workflow/blob/master/notion/README.md
Please refer to this docs.

Actually, I do not use this workflow and Notion too.
Becus it is not good to me.
So I will not update this workflow anymore.
Please use this workflows: https://github.com/wrjlewis/notion-search-alfred-workflow

Thanks!!
